require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

Style/Documentation:
  Enabled: false
